### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by july12123** [timotejroiko/discord.js-light#20]
we were going to switch our bot to discord.js light but one issue stopped us.
when looking for permissions on a channel for our bot the bitfield that returns is always 0.

**Comment by july12123** [comment]
it just started working out oh nowhere but keep this in mind.

**Comment by timotejroiko** [comment]
hey july, in order to check for permissions in channels there are some things you have to keep in mind:
besides the channel in question, both guild roles and channel permissionOverwrites need to be available which, depending on your client options, may need to be fetched separately.

There are several ways to achieve this depending on the specific caches you have enabled in your client options, feel free to join my discord if you need any troubleshooting :)
