### ISSUE TITLE
Migration from discord.js

### ISSUE THREAD

**Issue by atomheartother** [timotejroiko/discord.js-light#21]
Hey!

I'm the owner of [a fairly large Discord bot](https://top.gg/bot/433615162394804224), and I'm considering migrating my code from `discord.js` to `discord.js-light`, because their memory usage is getting absolutely stupid at 7k+ servers.

I have a few questions:
- Are there *ANY* API differences and gotchas I should be looking out for while I switch to this library, or is it literally just a drop-in replacement without caching? I assume I do have to make sure data is in cache now before pulling it, which i could basically avoid before since `discord.js` caches everything, but I mean anything other than that.
- Would you be interested in migrating `discord.js-light`'s codebase to Typescript? If i ever find the courage I might be interested in doing that, doesn't seem like a huge amount of work from what I've seen.
- Are github issues the best way to contact you? In case I have problems & bugs as I migrate my project, I wanna make sure I ask in the right place.

**Comment by timotejroiko** [comment]
hey there,
All differences should be explained in the readme unless i forgot something. As for typescript, im personally not a ts user, and since discord.js itself is not using it (yet) i didnt give it much thought either, but feel free to explore such endeavor. Im usually more active on discord, feel free to dm me or join my support server, otherwise i usually respond here as well within a day or two.
cheers!
