### ISSUE TITLE
v13

### ISSUE THREAD

**Issue by colenh** [timotejroiko/discord.js-light#63]
When will discord.js-light support v13?

**Comment by timotejroiko** [comment]
master version supports v13, you can install it with `npm install timotejroiko/discord.js-light`

when v13 is officially released, then discord.js-light v4 will also be released.

**Comment by edazpotato** [comment]
Will it work with the recent removal of `Structures` from Discord.JS? I'm asking because I noticed that that seems to be how this library works:
![image](https://user-images.githubusercontent.com/46797041/125150919-683be880-e197-11eb-86b4-d85498f5e064.png)

Where they removed Structures: [#6027](https://github.com/discordjs/discord.js/pull/6027)

**Comment by timotejroiko** [comment]
there are other ways to make it work
