### ISSUE TITLE
Kicking people doesn't work

### ISSUE THREAD

**Issue by PhoenixDiscord** [timotejroiko/discord.js-light#7]
I moved to `discord.js-light` because I'm forced to use a Raspberry Pi Zero for my Discord bots. It works better than I expected it to but I'm facing a few annoying issues - kicking and banning people doesn't work.

Here's my kick command:

```
		const { MessageEmbed } = require('discord.js-light');
		if (message.member.hasPermission('KICK_MEMBERS')) {
			const user = message.mentions.users.first();
			if (user) {
				const member = message.guild.member(user);
				if (member) {
					member
						.kick('Kicked by an administrator.')
						.then(() => {
							const kicked = new MessageEmbed()
								.addField(`${user.tag}`, 'Kicked successfully!');
							message.channel.send(kicked);
						})
						.catch(err => {
							message.reply('An error occured!');
							console.error(err);
						});
				}
				else {
					message.reply('This user is not in your server!');
				}
			}
			else {
				message.reply('You don\'t have permission to kick this user!');
			}
		}
```

If it's run with `kick <USER>`, it doesn't do anything. The same thing happens with the ban command.

**Comment by timotejroiko** [comment]
hey there,
which version are you using? If v3, which client options are you using?
Checking permissions requires roles to be cached (`cacheRoles:true` in v3).
Also, instead of getting the target user and then converting it to a member, get the member directly from the message (`message.mentions.members.first()`) otherwise it will try to look for it in the member cache and likely not find it.

**Comment by PhoenixDiscord** [comment]
I used v3 with all caching disabled. After reading your response I made it cache the roles and did some stuff with the code but it still didn't work so I gave up and moved to discord.js. <sub>Sorry for bothering you.</sub>
